#data types
student_name="vedika"
student_age=17
student_height=6.2
student_person=True
student_result=None
print(type(student_name))
print(type(student_age))
print(type(student_height))
print(type(student_person))
print(type(student_result))
a=50
b=50.0
c="50"
print(type(a),type(b),type(c))
x=True
y="True"
print(type(x),type(y))
v=None
z="None"
print(type(v),type(z))
value=10
Value=10.0
VAlue="10"
VALue=True
VALUe="true"
VALUE=None
valuE="None"
print(type(valuE),type(value),type(VALUe),type(VALue))