
name=input("enter your name:")
print(f"my name is {name}")
age=input("enter your age:")
print(f"my age is {age}")
print(type(input(age)))
#type of input is always string so we need to convert it into int or float if we want to perform any mathematical operation on it.
first_name,last_name=input("enter your first name and last name:").split()
print(f"my first name is {first_name} and my last name is {last_name}")
name=input("enter your name:")
city=input("enter your city:")
collage=input("enter your college name:")
print(f"my name is {name}, I live in {city}, and I study at {collage}.")
#python program to take multiple inputs from user in one line and store them in a list
numbers=input("enter multiple numbers separated by space:").split()
print(f"the numbers you entered are: {numbers}")
print(int("25"))
print(float("25.5"))
print(str(100))
a=int("78")
print(type(a))
b=float("78.5")
print(type(b))


a = input("enter first number: ")
b = input("enter second number: ")
print(int(a) + int(b))
product_name = input("enter product name: ")
price = float(input("enter price: "))
quantity = int(input("enter quantity: "))
total_price = price * quantity
print("A", "B", "C")
print("2026", "08", "19" , sep="-")
print("Hello world", end=" ")
print(f"First number: {a}")
print(f"Second number: {b}")
print(f"Sum: {int(a) + int(b)}")
print(f"Total price for {quantity} {product_name}(s) is: {total_price}")
name=int(input("enter your name:"))
age=int(input("enter your age:"))
marks=float(input("enter your marks:"))

#student details
student_name=input("enter your student_name:")
student_age=int(input("enter your student_age:"))
student_marks=float(input("enter your student_marks:"))
print(f"Student Name: {student_name}")
print(f"Student Age: {student_age}")
print(f"Student Marks: {student_marks}")
name=input("enter your name:")
city=input("enter your city:")
print(f"My name is {name} and I live in {city}.")
height=float(input("enter your height in meters:"))
weight=float(input("enter your weight in kilograms:"))
print(f"My height is {height} meters and my weight is {weight} kilograms.")